// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrPudNqOv-LF-aeiwG2LlXFddnE_pV_cw',
    appId: '1:220523840567:web:2064dd6a4b26d8d305ebb2',
    messagingSenderId: '220523840567',
    projectId: 'bt1-tuan11',
    authDomain: 'bt1-tuan11.firebaseapp.com',
    storageBucket: 'bt1-tuan11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX1wK0wELSakrrzR2-EuTYTGXXWEw2DIM',
    appId: '1:220523840567:android:a7c6e6b9dff8547205ebb2',
    messagingSenderId: '220523840567',
    projectId: 'bt1-tuan11',
    storageBucket: 'bt1-tuan11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoBNhvOI4YlKfMKHu0R0qn4LwwWNhjpOU',
    appId: '1:220523840567:ios:cb8820f2dd7efdab05ebb2',
    messagingSenderId: '220523840567',
    projectId: 'bt1-tuan11',
    storageBucket: 'bt1-tuan11.firebasestorage.app',
    iosBundleId: 'com.example.bt1Tuan11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoBNhvOI4YlKfMKHu0R0qn4LwwWNhjpOU',
    appId: '1:220523840567:ios:cb8820f2dd7efdab05ebb2',
    messagingSenderId: '220523840567',
    projectId: 'bt1-tuan11',
    storageBucket: 'bt1-tuan11.firebasestorage.app',
    iosBundleId: 'com.example.bt1Tuan11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrPudNqOv-LF-aeiwG2LlXFddnE_pV_cw',
    appId: '1:220523840567:web:732c86ccf9ac829605ebb2',
    messagingSenderId: '220523840567',
    projectId: 'bt1-tuan11',
    authDomain: 'bt1-tuan11.firebaseapp.com',
    storageBucket: 'bt1-tuan11.firebasestorage.app',
  );
}
